export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTSBYCATEGORIESID = "GET_PRODUCTSBYCATEGORIESID";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
